// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFY-D-pnrl1LlE9F7ETe9-C7iNexRNops',
    appId: '1:222192939392:android:3317c2a5fabe3d6a2c1165',
    messagingSenderId: '222192939392',
    projectId: 'tapin-a79e6',
    storageBucket: 'tapin-a79e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3n5u8BBKy8zsPoWQHN_QvOnBsiRIckY',
    appId: '1:222192939392:ios:2b0a1b1f614169892c1165',
    messagingSenderId: '222192939392',
    projectId: 'tapin-a79e6',
    storageBucket: 'tapin-a79e6.firebasestorage.app',
    iosBundleId: 'com.example.tapinGolf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3n5u8BBKy8zsPoWQHN_QvOnBsiRIckY',
    appId: '1:222192939392:ios:2b0a1b1f614169892c1165',
    messagingSenderId: '222192939392',
    projectId: 'tapin-a79e6',
    storageBucket: 'tapin-a79e6.firebasestorage.app',
    iosBundleId: 'com.example.tapinGolf',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe65py-n-iQK4Dh2dKOXDd_0PRpFLn1Y4',
    appId: '1:222192939392:web:85807f0716305f7a2c1165',
    messagingSenderId: '222192939392',
    projectId: 'tapin-a79e6',
    authDomain: 'tapin-a79e6.firebaseapp.com',
    storageBucket: 'tapin-a79e6.firebasestorage.app',
    measurementId: 'G-HC8XTDLPCN',
  );

}